#!/usr/bin/env python3
"""Generate the LKZ-1 (ICT/SMC London Killzone Asian-Range Sweep) strategy diagrams.

Pure schematic artwork (no market data). Deterministic (seeded) so the committed
figures can be regenerated byte-similar at any time:

    python3 scripts/generate_lkz_diagrams.py

Outputs (PNG for preview, SVG for docs embedding) to docs/strategy/assets/lkz/.
Source strategy: docs/strategy/ICT-SMC-LONDON-KZ-ASIAN-SWEEP-v1.md
Machine spec:    specs/lkz-v1.yaml
"""
import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch, Polygon, Rectangle

# --------------------------------------------------------------------------- #
# Theme
# --------------------------------------------------------------------------- #
BG = "#0d1117"
PANEL = "#141a22"
GRID = "#232a33"
TXT = "#e6edf3"
SUB = "#9aa7b4"
BULL = "#26a69a"
BEAR = "#ef5350"
CY = "#58a6ff"
PU = "#bc8cff"
OR = "#f0883e"
YE = "#e3b341"
RD = "#f85149"
GN = "#3fb950"
WH = "#f0f6fc"

plt.rcParams.update(
    {
        "figure.facecolor": BG,
        "axes.facecolor": PANEL,
        "savefig.facecolor": BG,
        "text.color": TXT,
        "axes.edgecolor": GRID,
        "axes.labelcolor": TXT,
        "xtick.color": SUB,
        "ytick.color": SUB,
        "font.size": 10.5,
        "svg.fonttype": "path",  # portable SVG (text as paths)
    }
)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "docs", "strategy", "assets", "lkz"))
os.makedirs(OUT, exist_ok=True)


def save(fig, name):
    png = os.path.join(OUT, name + ".png")
    svg = os.path.join(OUT, name + ".svg")
    fig.savefig(png, dpi=110, bbox_inches="tight", facecolor=fig.get_facecolor())
    fig.savefig(svg, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)
    print("wrote", png)
    print("wrote", svg)


def candles(ax, data, w=0.62, lw=1.2, z=5):
    """data: list of (o, h, l, c); x positions = 0..n-1."""
    for i, (o, h, lo, c) in enumerate(data):
        col = BULL if c >= o else BEAR
        ax.plot([i, i], [lo, h], color=col, lw=lw, zorder=z, solid_capstyle="butt")
        y0, y1 = sorted((o, c))
        ax.add_patch(
            Rectangle(
                (i - w / 2, y0),
                w,
                max(y1 - y0, 1e-9),
                facecolor=col,
                edgecolor=col,
                zorder=z + 1,
            )
        )


def level(ax, x0, x1, y, color, label=None, ls=(0, (6, 4)), lw=1.4, z=6,
          lab_dx=0.4, lab_side="right", lab_color=None, fs=9):
    ax.plot([x0, x1], [y, y], color=color, ls=ls, lw=lw, zorder=z)
    if label:
        xa = x1 + lab_dx if lab_side == "right" else x0 - lab_dx
        ha = "left" if lab_side == "right" else "right"
        ax.text(xa, y, label, color=lab_color or color, fontsize=fs, va="center",
                ha=ha, zorder=z + 2)


def zone(ax, x0, x1, y0, y1, color, alpha=0.22, label=None, lab_xy=None,
         lab_color=None, fs=9, z=2, border=True):
    ax.add_patch(
        Rectangle(
            (x0, y0), x1 - x0, y1 - y0,
            facecolor=color, alpha=alpha,
            edgecolor=color if border else "none",
            lw=1.0, zorder=z,
        )
    )
    if label:
        ax.text(*(lab_xy or ((x0 + x1) / 2, (y0 + y1) / 2)), label,
                color=lab_color or color, fontsize=fs, ha="center", va="center",
                zorder=z + 3)


def arrow(ax, x0, y0, x1, y1, color, lw=2.2, style="-|>", z=20):
    ax.add_patch(
        FancyArrowPatch((x0, y0), (x1, y1), arrowstyle=style, mutation_scale=16,
                        color=color, lw=lw, zorder=z)
    )


# --------------------------------------------------------------------------- #
# FIG 1 - Daily time map
# --------------------------------------------------------------------------- #
def fig1():
    fig, ax = plt.subplots(figsize=(15.6, 5.6))
    fig.subplots_adjust(left=0.03, right=0.985, top=0.80, bottom=0.13)

    t0, t1 = 18.0, 30.5  # 18:00 D0 .. 06:30 D+1 (hours, 24 = midnight)
    ax.set_xlim(t0, t1)
    ax.set_ylim(-3.4, 4.4)
    ax.axis("off")

    def X(h):
        return h

    # ---- session band ---------------------------------------------------- #
    band = [
        # (h0, h1, color, alpha, title, sub, txtcol)
        (20.0, 24.0, PU, 0.30, "ASIAN RANGE  20:00–00:00",
         "Q1 ACCUMULATION — must RANGING (marked at 01:00)", WH),
        (24.0, 25.5, SUB, 0.16, "",
         "", SUB),
        (25.5, 27.5, RD, 0.30, "MANIPULATION WINDOW",
         "01:30–03:30 — Q2 — sweep must print INSIDE", WH),
        (27.5, 31.0, CY, 0.18, "DISTRIBUTION  03:30–07:00",
         "trend leg toward the draw on liquidity", WH),
    ]
    for h0, h1, col, al, ti, su, tc in band:
        ax.add_patch(Rectangle((h0, 0.6), h1 - h0, 2.4, facecolor=col, alpha=al,
                               edgecolor=col, lw=1.2, zorder=2))
        if ti:
            ax.text((h0 + h1) / 2, 2.62, ti, color=tc, fontsize=10.5,
                    ha="center", va="center", weight="bold", zorder=6)
            ax.text((h0 + h1) / 2, 1.95, su, color=tc, fontsize=8.8,
                    ha="center", va="center", zorder=6)

    # midnight open flag
    ax.axvline(24.0, color=YE, lw=2.0, zorder=5)
    ax.scatter([24.0], [3.05], marker="v", s=110, color=YE, zorder=6)
    ax.text(23.75, 3.35, "MIDNIGHT OPEN 00:00\n(short only above · long only below)",
            color=YE, fontsize=9, ha="right", va="bottom", zorder=6)

    # prep marker 01:00
    ax.scatter([25.0], [0.6], marker="^", s=110, color=OR, zorder=6)
    ax.annotate("BE AT CHART 01:00\nmark Asian Hi/Lo · POIs · liquidity map · bias",
                xy=(25.0, 0.55), xytext=(25.0, -1.15), color=OR, fontsize=9,
                ha="center", va="top",
                arrowprops=dict(arrowstyle="-|>", color=OR, lw=1.6), zorder=6)

    # entry marker inside window (clear of the band subtitle)
    ax.scatter([26.6], [1.10], marker="*", s=260, color=GN, zorder=7)
    ax.text(27.05, 0.82, "LTF entry (M1–M5)", color=GN, fontsize=8.8,
            ha="left", va="center", zorder=7)

    # invalid-sweep note (above the band, clear of the midnight-open line)
    ax.scatter([24.9], [3.22], marker="X", s=90, color=RD, zorder=7)
    ax.text(25.25, 3.22, "sweep before 01:30 = INVALID (skip)", color=RD,
            fontsize=8.6, ha="left", va="center", zorder=7)

    # NY continuation band note
    ax.add_patch(Rectangle((31.0, 0.6), 0.4, 2.4, facecolor=GN, alpha=0.25,
                           edgecolor=GN, lw=1.0, zorder=2))
    ax.text(31.45, 1.70, "→ NY KZ 07:00–10:00:\noptional continuation entry\n(mitigate London FVG)",
            color=GN, fontsize=8.8, va="center", zorder=6)

    # time axis
    ticks = [(18, "18:00"), (20, "20:00\nAsia opens"), (22, "22:00"),
             (24, "00:00"), (25, "01:00"), (26, "02:00"), (27, "03:00"),
             (28, "04:00"), (29.5, "05:30"), (31, "07:00")]
    for h, lab in ticks:
        ax.plot([h, h], [0.45, 0.6], color=SUB, lw=1.2, zorder=4)
        ax.text(h, 0.1, lab, color=SUB, fontsize=8.4, ha="center", va="top")
    ax.annotate("", xy=(30.6, 0.52), xytext=(17.9, 0.52),
                arrowprops=dict(arrowstyle="-|>", color=SUB, lw=1.2))
    ax.text(18.0, -0.75, "all times America/New_York — spec normalises to UTC, DST-adjusted "
            "(specs/lkz-v1.yaml §time_model)", color=SUB, fontsize=9, ha="left")

    ax.set_title("LKZ-1 · Daily Time Map — ICT Quarterly Theory applied to one NY day",
                 color=WH, fontsize=14, weight="bold", pad=14)
    save(fig, "lkz-fig1-time-map")


# --------------------------------------------------------------------------- #
# FIG 2 - Anatomy of the A+ short (hero chart)
# --------------------------------------------------------------------------- #
def fig2():
    rng = np.random.default_rng(7)

    N = 74
    O = np.zeros(N)
    H = np.zeros(N)
    L = np.zeros(N)
    C = np.zeros(N)

    # --- scripted skeleton (close-to-close anchors), indices = M5 bars ---- #
    anchors = {
        0: 1.0892, 2: 1.0869, 4: 1.0889, 7: 1.0895, 9: 1.0884, 12: 1.0898,
        15: 1.0888, 18: 1.0903, 20: 1.0896, 22: 1.0892, 25: 1.0899, 27: 1.0888,
        30: 1.0889, 33: 1.0889, 36: 1.0893, 38: 1.0898, 40: 1.0912, 42: 1.0927,
        43: 1.0934, 44: 1.0922, 45: 1.0902, 46: 1.0913, 47: 1.0924, 48: 1.0919,
        50: 1.0904, 52: 1.0898, 54: 1.0890, 57: 1.0884, 60: 1.0879, 63: 1.0870,
        66: 1.0863, 69: 1.0849, 73: 1.0851,
    }
    idx = sorted(anchors)
    closes = np.interp(np.arange(N), idx, [anchors[i] for i in idx])
    closes += rng.normal(0, 0.00016, N)

    prev = anchors[0]
    for i in range(N):
        o = prev
        c = closes[i]
        hi = max(o, c) + abs(rng.normal(0, 0.00028)) + 0.00008
        lo = min(o, c) - abs(rng.normal(0, 0.00028)) - 0.00008
        O[i], H[i], L[i], C[i] = o, hi, lo, c
        prev = c

    # --- exact key bars (geometry the spec references) -------------------- #
    key = {
        2:  (1.0876, 1.0884, 1.0865, 1.0880),  # pre-Asia low (failure swing origin)
        7:  (1.0890, 1.0897, 1.0886, 1.0894),  # Asia high 1
        9:  (1.0893, 1.0895, 1.0880, 1.0887),  # Asia low 1
        12: (1.0890, 1.0901, 1.0888, 1.0898),  # Asia high 2 (higher)
        15: (1.0896, 1.0898, 1.0884, 1.0891),  # Asia low 2 (higher low)
        18: (1.0894, 1.0906, 1.0893, 1.0903),  # Asia high 3 (highest)
        22: (1.0896, 1.0898, 1.0889, 1.0894),  # Asia low 3 (higher low)
        33: (1.0890, 1.0912, 1.0887, 1.0889),  # INVALID pre-window sweep
        42: (1.0920, 1.0928, 1.0914, 1.0927),
        43: (1.0928, 1.0936, 1.0926, 1.0934),  # THE sweep (into POI)
        44: (1.0933, 1.0935, 1.0920, 1.0922),  # CSD: close below prior low
        45: (1.0920, 1.0916, 1.0898, 1.0902),  # impulse -> FVG [1.0916,1.0926]
        47: (1.0913, 1.0926, 1.0910, 1.0924),  # tags FVG CE
        48: (1.0924, 1.0927, 1.0916, 1.0919),  # rejection
    }
    for i, (o, h, lo, c) in key.items():
        O[i], H[i], L[i], C[i] = o, h, lo, c

    data = list(zip(O, H, L, C))

    # --- price levels ------------------------------------------------------ #
    ASIA_HI = 1.0906
    ASIA_LO = 1.0880
    POI_LO, POI_HI = 1.0930, 1.0938
    FVG_LO, FVG_HI = 1.0916, 1.0926
    MNO = 1.0892
    POOL = 1.0865
    PDL = 1.0844
    SWEEP_HI = 1.0936
    SL = 1.0940
    E_CSD = 1.0922   # close of bar 44
    E_CE = 1.0921    # FVG CE ~ (1.0916+1.0926)/2
    U = 0.0001       # "unit" for R text

    fig, ax = plt.subplots(figsize=(16, 9.6))
    fig.subplots_adjust(left=0.045, right=0.99, top=0.90, bottom=0.07)

    # session shading
    ax.axvspan(-0.6, 28, color=PU, alpha=0.055, zorder=0)
    ax.axvspan(36, 45.5, color=RD, alpha=0.075, zorder=0)
    ax.axvspan(45.5, 73.6, color=CY, alpha=0.05, zorder=0)
    ax.text(13, 1.0962, "ASIAN RANGE  20:00–00:00  (Q1 · must be RANGING)",
            color=PU, fontsize=10.5, ha="center", weight="bold")
    ax.text(40.75, 1.0962, "MANIPULATION\n01:30–03:30 (Q2)", color=RD,
            fontsize=9.5, ha="center", weight="bold")
    ax.text(59.5, 1.0962, "DISTRIBUTION  →  draw on liquidity", color=CY,
            fontsize=10.5, ha="center", weight="bold")

    # POI + FVG zones
    zone(ax, -0.6, 49.5, POI_LO, POI_HI, OR, 0.20,
         label="HTF POI — unmitigated M15/H1 FVG + OB  (above Asian range & above midnight open)",
         lab_xy=(10.4, (POI_LO + POI_HI) / 2), lab_color=OR, fs=9.4)
    zone(ax, 43.5, 60, FVG_LO, FVG_HI, YE, 0.20,
         label="LTF FVG\n(created by the shift)", lab_xy=(57.5, (FVG_LO + FVG_HI) / 2),
         lab_color=YE, fs=8.6)

    candles(ax, data)

    # levels (lines end at x=76; names on the chart, R-ladder on the RIGHT)
    LE = 76.0
    level(ax, 4, LE, ASIA_HI, CY, "Asian High (swept BSL)")
    level(ax, 4, LE, ASIA_LO, CY, None)
    ax.text(42.6, ASIA_LO + 0.00008, "Asian Low", color=CY, fontsize=9, va="bottom")
    level(ax, 28, LE, MNO, YE, None, ls=(0, (2, 2)))
    ax.text(42.6, MNO + 0.00008, "Midnight Open", color=YE, fontsize=9, va="bottom")
    level(ax, 0, LE, POOL, PU, None)
    ax.text(0.4, POOL + 0.00006, "SSL pool — failure-swing (low-resistance) liquidity",
            color=PU, fontsize=9, va="bottom")
    level(ax, 0, LE, PDL, WH, None)
    ax.text(0.4, PDL - 0.00006, "Previous Day Low", color=WH, fontsize=9, va="top")
    level(ax, 42, 60, SL, RD, "SL — above POI + buffer", ls=(0, (4, 2)), lw=1.6)

    # invalid pre-window sweep marker
    ax.annotate("✘ 00:40 sweep — BEFORE window → invalid",
                xy=(32.9, 1.09135), xytext=(26.6, 1.09195), color=RD, fontsize=8.8,
                ha="center", va="bottom",
                arrowprops=dict(arrowstyle="-|>", color=RD, lw=1.6))

    # the real sweep marker
    ax.annotate("✔ THE SWEEP — Asian High taken INTO the POI at ~02:10",
                xy=(43, SWEEP_HI + 0.00004), xytext=(34.6, 1.0950),
                color=GN, fontsize=9.6, weight="bold",
                arrowprops=dict(arrowstyle="-|>", color=GN, lw=1.8))

    # entries
    arrow(ax, 46.2, 1.09255, 44.6, 1.09238, GN, lw=2.0)
    ax.text(46.4, 1.09266, "E-B · CSD entry (close of the shift candle)",
            color=GN, fontsize=9.0, va="center")
    arrow(ax, 50.6, 1.09090, 48.6, 1.09199, YE, lw=2.0)
    ax.text(50.8, 1.09080, "E-C/D · FVG CE 50% mitigation entry",
            color=YE, fontsize=9.0, va="center")

    # BSL/SSL annotations
    ax.annotate("highs kept getting taken during Asia\n→ liquidity above PURGED (high-resistance)",
                xy=(12.1, 1.09045), xytext=(3.2, 1.09185), color=CY, fontsize=8.8,
                arrowprops=dict(arrowstyle="-|>", color=CY, lw=1.2))
    for x, y in [(9.4, 1.08752), (15.4, 1.08792), (22.4, 1.08842)]:
        ax.text(x, y, "$", color=PU, fontsize=11, ha="center", weight="bold")
    ax.text(64.8, 1.08610, "$ $ $", color=PU, fontsize=12, ha="center", weight="bold")

    # R ladder on the right (computed from drawn geometry, CE entry)
    r0 = SL - E_CE
    ladder = [("P1", MNO, YE), ("TP1", ASIA_LO, CY), ("TP2", POOL, PU), ("TP3", PDL, WH)]
    LX = 77.6
    ax.text(LX, 1.0950, "R-ladder (E-C/D entry,\ngeometry as drawn)",
            color=SUB, fontsize=8.6, ha="left", va="top")
    for name, y, col in ladder:
        r = (E_CE - y) / r0
        ax.text(LX, y, f"{name}  ≈ {r:.1f}R", color=col, fontsize=9.4,
                va="center", weight="bold")
    ax.text(LX, 1.0922, f"SL {SL:.4f}\nrisk {r0 / U:.0f}u", color=RD,
            fontsize=8.4, va="center")
    ax.text(LX, 1.0836, "spec gate G5: final structural\nTP must be ≥ 3R (partials\nmay sit below)", color=SUB,
            fontsize=7.8, va="top")

    ax.set_xlim(-1, 85)
    ax.set_ylim(1.0832, 1.0980)
    ax.set_xticks([])
    ax.set_yticks([])
    for s in ax.spines.values():
        s.set_visible(False)

    ax.set_title("LKZ-1 · Anatomy of the A+ short — Asian-range sweep into HTF POI "
                 "inside 01:30–03:30 (schematic, M5)",
                 color=WH, fontsize=14, weight="bold", pad=16)
    ax.text(0, 1.08345,
            "Checklist gates shown: ranging Asia ✓ · liquidity map ✓ · HTF POI above range ✓ · above midnight open ✓ · "
            "sweep inside window ✓ · LTF shift entry ✓ · SL defined ✓ → manage: P1 @MNO, TP1 Asia Low, TP2 SSL pool, TP3 PDL.",
            color=SUB, fontsize=8.8, ha="left")
    save(fig, "lkz-fig2-anatomy-short")


# --------------------------------------------------------------------------- #
# FIG 3 - Entry models (LTF triggers)
# --------------------------------------------------------------------------- #
def fig3():
    fig, axs = plt.subplots(2, 2, figsize=(15.6, 9.4))
    fig.subplots_adjust(left=0.04, right=0.98, top=0.90, bottom=0.06, hspace=0.34, wspace=0.10)

    models = [
        dict(id="E-A", name="TURTLE SOUP (risk entry)", col=OR,
             desc="Enter AT the sweep inside the POI — no confirmation.\n"
                  "Smallest stop, highest stop-out rate. Limit at POI CE."),
        dict(id="E-B", name="CSD — CHANGE IN STATE OF DELIVERY", col=GN,
             desc="After the sweep, one exec-TF candle engulfs the last\n"
                  "up-leg candle and CLOSES through its low → enter at close."),
        dict(id="E-C", name="MSS + FVG CE MITIGATION", col=CY,
             desc="Close through the last LTF swing (MSS) must print an FVG →\n"
                  "limit at FVG CE (50%). Video's workhorse entry."),
        dict(id="E-D/E", name="FIRST FVG / INVERSE FVG CONTINUATION", col=PU,
             desc="First FVG created off the POI → CE entry. If price breaks\n"
                  "through it → inverted FVG / breaker retest = re-entry."),
    ]

    for ax, m in zip(axs.ravel(), models):
        ax.set_xlim(-0.8, 13.4)
        ax.set_ylim(0.0, 10.0)
        ax.set_xticks([])
        ax.set_yticks([])
        for s in ax.spines.values():
            s.set_edgecolor(GRID)
        ax.set_title(f"{m['id']} · {m['name']}", color=m["col"], fontsize=11.5,
                     weight="bold", loc="left", pad=22)
        ax.text(0, 10.55, "", fontsize=1)  # spacing

    # ---- E-A turtle soup ------------------------------------------------- #
    ax = axs[0, 0]
    zone(ax, -0.6, 5.4, 6.4, 8.0, OR, 0.18, label="HTF POI", lab_xy=(1.2, 7.2), fs=9)
    level(ax, 0, 12.8, 5.6, CY, "Asian High", fs=8)
    d = [
        (4.0, 4.6, 3.8, 4.5), (4.5, 5.2, 4.4, 5.0), (5.0, 5.7, 4.9, 5.5),
        (5.5, 7.3, 5.4, 6.9),           # sweep bar into POI, closes back
        (6.9, 7.15, 6.0, 6.2), (6.2, 6.4, 4.9, 5.1), (5.1, 5.3, 3.9, 4.1),
        (4.1, 4.3, 3.0, 3.2),
    ]
    candles(ax, d)
    ax.text(4.2, 7.45, "sweep", color=OR, fontsize=9)
    arrow(ax, 6.3, 8.6, 4.15, 6.9, GN, lw=2.0)
    ax.text(6.5, 8.65, "ENTRY (limit @ POI CE)", color=GN, fontsize=9, va="center")
    level(ax, 4.6, 11.5, 7.5, RD, "SL above sweep", fs=8)

    # ---- E-B CSD ---------------------------------------------------------- #
    ax = axs[0, 1]
    zone(ax, -0.6, 5.4, 6.6, 8.2, OR, 0.18, label="HTF POI", lab_xy=(1.2, 7.4), fs=9)
    level(ax, 0, 12.8, 5.6, CY, "Asian High", fs=8)
    d = [
        (4.0, 4.6, 3.8, 4.5), (4.5, 5.1, 4.4, 5.0),
        (5.0, 6.9, 4.9, 6.6),           # last up candle (origin of buy program)
        (6.6, 7.6, 6.5, 7.35),          # sweep extreme
        (7.3, 7.4, 4.7, 4.85),          # CSD: engulfs prev body, closes < its low
        (4.85, 5.4, 3.6, 3.8), (3.8, 4.0, 2.8, 3.0),
    ]
    candles(ax, d)
    ax.text(4.25, 7.75, "sweep", color=OR, fontsize=9)
    ax.text(12.8, 3.3, "CSD candle: engulfs the buy-\nleg and closes below its low",
            color=GN, fontsize=8.4, ha="right", va="top")
    ax.annotate("", xy=(4.9, 4.75), xytext=(8.1, 3.6),
                arrowprops=dict(arrowstyle="-|>", color=GN, lw=1.2))
    arrow(ax, 8.2, 6.9, 6.3, 4.95, GN, lw=2.0)
    ax.text(8.4, 7.1, "ENTRY @ close", color=GN, fontsize=9, va="center")
    level(ax, 5.4, 11.9, 7.75, RD, "SL above POI", fs=8)

    # ---- E-C MSS + FVG CE ------------------------------------------------- #
    ax = axs[1, 0]
    zone(ax, -0.6, 3.4, 6.8, 8.3, OR, 0.18, label="HTF POI", lab_xy=(0.9, 7.55), fs=9)
    level(ax, 0, 12.8, 5.7, CY, "Asian High", fs=8)
    d = [
        (4.2, 4.8, 4.0, 4.7), (4.7, 5.3, 4.6, 5.2), (5.2, 5.5, 4.8, 4.9),  # swing low at 4.8
        (4.9, 7.9, 4.85, 7.6),          # sweep
        (7.6, 7.7, 6.3, 6.4),
        (6.4, 6.6, 4.5, 4.6),           # MSS close < 4.8
        (4.6, 4.9, 3.6, 3.8),           # impulse -> FVG (4.9..6.3)
        (3.8, 5.7, 3.7, 5.55),          # retrace into CE
        (5.55, 5.75, 4.2, 4.3),         # rejection
        (4.3, 4.5, 2.9, 3.1),
    ]
    candles(ax, d)
    level(ax, 2, 8.5, 4.8, YE, None, ls=(0, (3, 2)))
    ax.text(1.9, 4.42, "last LTF swing →\nMSS on close below", color=YE, fontsize=7.8,
            ha="left", va="top")
    zone(ax, 6.5, 12.4, 4.9, 6.15, YE, 0.16, label="FVG", lab_xy=(11.55, 5.95), fs=8.4)
    level(ax, 6.5, 12.4, 5.52, YE, None, ls=(0, (2, 2)), lw=1.1)
    arrow(ax, 9.6, 7.15, 8.35, 5.7, GN, lw=2.0)
    ax.text(9.8, 7.3, "ENTRY @ FVG CE 50%", color=GN, fontsize=9, va="center")
    level(ax, 4.0, 11.9, 8.0, RD, "SL above sweep high", fs=8)

    # ---- E-D/E first FVG / IFVG ------------------------------------------- #
    ax = axs[1, 1]
    zone(ax, -0.6, 3.4, 7.0, 8.4, OR, 0.18, label="HTF POI", lab_xy=(0.9, 7.7), fs=9)
    level(ax, 0, 12.8, 5.8, CY, "Asian High", fs=8)
    d = [
        (4.4, 5.0, 4.2, 4.9), (4.9, 5.5, 4.8, 5.4),
        (5.4, 8.0, 5.3, 7.7),           # sweep
        (7.7, 7.8, 6.4, 6.5),
        (6.5, 6.7, 5.0, 5.1),           # impulse: first FVG 5.5..6.4
        (5.1, 5.2, 3.7, 3.85),          # breaks THROUGH the FVG -> IFVG
        (3.85, 5.75, 3.75, 5.6),        # retest of inverted zone
        (5.6, 5.8, 4.4, 4.55),
        (4.55, 4.75, 3.0, 3.2),
    ]
    candles(ax, d)
    zone(ax, 4.5, 7.6, 5.5, 6.4, PU, 0.15, label="first FVG → inverted", lab_xy=(6.05, 5.95), fs=8.0)
    arrow(ax, 8.6, 7.0, 7.15, 5.75, GN, lw=2.0)
    ax.text(8.8, 7.15, "ENTRY @ IFVG retest", color=GN, fontsize=9, va="center")
    level(ax, 3.6, 11.9, 8.05, RD, "SL above sweep high", fs=8)

    fig.suptitle("LKZ-1 · Lower-timeframe entry models (M1–M5, M3 preferred) — one signal per structure",
                 color=WH, fontsize=14, weight="bold", y=0.975)
    for ax, m in zip(axs.ravel(), models):
        ax.text(-0.7, -0.75, m["desc"], color=SUB, fontsize=8.6, va="top", wrap=True)
    save(fig, "lkz-fig3-entry-models")


# --------------------------------------------------------------------------- #
# FIG 4 - Liquidity logic + Asian range filter
# --------------------------------------------------------------------------- #
def fig4():
    fig, axs = plt.subplots(1, 3, figsize=(16, 5.6))
    fig.subplots_adjust(left=0.03, right=0.985, top=0.82, bottom=0.09, wspace=0.10)

    for ax in axs:
        ax.set_xticks([])
        ax.set_yticks([])
        for s in ax.spines.values():
            s.set_edgecolor(GRID)

    # ---- panel A: high-resistance liquidity --------------------------------
    ax = axs[0]
    d = [
        (4.0, 5.0, 3.8, 4.8), (4.8, 5.4, 4.3, 4.5), (4.5, 5.2, 4.2, 5.0),
        (5.0, 6.2, 4.9, 6.0),           # higher high -> liquidity above taken
        (6.0, 6.1, 4.6, 4.8),           # rejection
        (4.8, 5.0, 3.9, 4.1),
    ]
    candles(ax, d)
    level(ax, 0, 6.9, 5.0, RD)
    arrow(ax, 1.05, 5.5, 1.0, 5.08, RD, lw=1.6)
    ax.text(0.4, 6.9, "✘ HIGH-RESISTANCE", color=RD, fontsize=11, weight="bold", va="bottom")
    ax.text(0.4, 4.30, "high swept, then rejected:\nliquidity PURGED above\n→ old level = poor draw",
            color=SUB, fontsize=8.6, va="top")
    ax.set_xlim(-0.6, 7.6)
    ax.set_ylim(3.2, 7.4)

    # ---- panel B: low-resistance liquidity ---------------------------------
    ax = axs[1]
    d = [
        (4.0, 4.5, 3.50, 3.7),          # low 1
        (3.7, 4.9, 3.60, 4.8),
        (4.8, 5.1, 3.55, 3.8),          # low 2 ~ equal (liquidity pool building)
        (3.8, 5.2, 3.70, 5.1),
        (5.1, 5.3, 3.95, 4.1),          # higher low -> failure swing
        (4.1, 5.35, 4.0, 5.3),
    ]
    candles(ax, d)
    level(ax, -0.5, 7.4, 3.5, PU)
    ax.plot([0, 2.0], [3.5, 3.6], color=PU, lw=1.0, ls=(0, (2, 2)))
    ax.plot([2.0, 4.0], [3.6, 3.95], color=PU, lw=1.0, ls=(0, (2, 2)))
    for x, y in ((0.2, 3.18), (2.1, 3.22)):
        ax.text(x, y, "$", color=PU, fontsize=13, ha="center", weight="bold")
    ax.text(0.4, 6.9, "✔ LOW-RESISTANCE", color=GN, fontsize=11, weight="bold", va="bottom")
    ax.text(0.3, 6.42, "low → equal low → higher low\n(failure swing): stops REST below\n"
            "each pool → an easy run:\nthe DRAW ON LIQUIDITY = target",
            color=SUB, fontsize=8.4, va="top")
    arrow(ax, 6.4, 5.7, 6.4, 3.75, PU, lw=2.0)
    ax.set_xlim(-0.6, 7.6)
    ax.set_ylim(2.9, 7.4)
    ax.set_title("Liquidity map — what is a valid draw?", color=WH, fontsize=12,
                 weight="bold", loc="left", x=-1.05, y=1.08)

    # ---- panel C: Asian session filter -------------------------------------- #
    ax = axs[2]
    d1 = [
        (4.5, 5.3, 4.2, 5.1), (5.1, 5.6, 4.4, 4.7), (4.7, 5.5, 4.5, 5.3),
        (5.3, 5.7, 4.6, 4.9), (4.9, 5.4, 4.3, 4.6), (4.6, 5.5, 4.5, 5.2),
    ]
    candles(ax, d1)
    level(ax, -0.5, 5.6, 5.62, GN, "range hi", fs=8)
    level(ax, -0.5, 5.6, 4.22, GN, "range lo", fs=8)
    ax.text(2.5, 7.0, "✔ RANGING → TRADE", color=GN, fontsize=10.5, ha="center", weight="bold")
    d2 = [(8.1 + i * 0.55, 8.35 + i * 0.55, 7.9 + i * 0.55, 8.3 + i * 0.55) for i in range(7)]
    candles(ax, d2, w=0.5)
    ax.plot([6.4, 11.7], [4.0, 9.6], color=RD, lw=1.4, ls=(0, (5, 3)))
    ax.text(9.3, 11.9, "✘ TRENDING → SKIP", color=RD, fontsize=10.5, ha="center", weight="bold")
    ax.text(5.7, 3.15, "spec gates: net-drift ≤ 35% of range · width ≤ 1.5×ATR₁₄(H1)\n"
            "· both range thirds touched (spec §asian_range)", color=SUB, fontsize=8.4,
            ha="center", va="top")
    ax.set_xlim(-0.6, 12.3)
    ax.set_ylim(2.8, 12.6)

    fig.suptitle("LKZ-1 · Liquidity quality + the ranging-Asia hard filter",
                 color=WH, fontsize=14, weight="bold", y=0.98)
    save(fig, "lkz-fig4-liquidity-logic")


# --------------------------------------------------------------------------- #
# FIG 5 - Decision pipeline (flowchart)
# --------------------------------------------------------------------------- #
def fig5():
    fig, ax = plt.subplots(figsize=(11.4, 15.6))
    fig.subplots_adjust(left=0.02, right=0.98, top=0.985, bottom=0.015)
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 150)
    ax.axis("off")

    X = 38.0          # main spine
    W_PROC, H_PROC = 44, 6.4
    W_DIA, H_DIA = 46, 8.0
    NOGO_X = 84.0

    def proc(y, lines, col=CY, w=W_PROC, h=H_PROC, fs=9.6):
        ax.add_patch(FancyBboxPatch((X - w / 2, y - h / 2), w, h,
                                    boxstyle="round,pad=0.42,rounding_size=1.2",
                                    facecolor=PANEL, edgecolor=col, lw=1.6, zorder=5))
        ax.text(X, y, lines, color=TXT, fontsize=fs, ha="center", va="center", zorder=6)

    def dia(y, lines, col=YE, w=W_DIA, h=H_DIA, fs=9.4):
        pts = [(X, y + h / 2), (X + w / 2, y), (X, y - h / 2), (X - w / 2, y)]
        ax.add_patch(Polygon(pts, closed=True, facecolor=PANEL, edgecolor=col,
                             lw=1.6, zorder=5))
        ax.text(X, y, lines, color=TXT, fontsize=fs, ha="center", va="center", zorder=6)

    def nogo(y, reason):
        ax.add_patch(FancyBboxPatch((NOGO_X - 13.5, y - 2.6), 27, 5.2,
                                    boxstyle="round,pad=0.3,rounding_size=1.0",
                                    facecolor="#2a1316", edgecolor=RD, lw=1.3, zorder=5))
        ax.text(NOGO_X, y, "NO-GO\n" + reason, color=RD, fontsize=8.0,
                ha="center", va="center", zorder=6)
        arrow(ax, X + W_DIA / 2, y, NOGO_X - 13.8, y, RD, lw=1.3)

    def down(y0, y1, label=None, col=SUB):
        arrow(ax, X, y0, X, y1, col, lw=1.6)
        if label:
            ax.text(X + 1.6, (y0 + y1) / 2, label, color=col, fontsize=8.4, va="center")

    proc(145, "UTC/DST NORMALISE  →  weekday Mon–Fri\n(all triggers evaluated on CLOSED candles)", col=SUB)
    down(141.8, 138)

    dia(134.5, "G1 · ASIAN RANGE 20:00–00:00 COMPLETE\nand RANGING? (drift ≤35%, width ≤1.5×ATR)")
    nogo(134.5, "trending Asia /\nweekend")
    down(130.5, 127.2)

    proc(124, "MAP: Asian Hi/Lo · failure-swing & equal-level\npools · HTF POIs (FVG/OB/BB on M15–H4)", col=PU)
    down(120.8, 118.4)

    dia(115, "G2 · DRAW ON LIQUIDITY?\nlow-resistance pool on ONE side")
    nogo(115, "no clean draw")
    down(111, 108.2)

    dia(104, "G3 · HTF POI on the sweep side,\nUNMITIGATED, on correct side of\nmidnight open & daily bias?")
    nogo(104, "no POI / wrong side\nof MNO / bias conflict")
    down(99.8, 96.6)

    proc(93.4, "WAIT WINDOW 01:30–03:30 NY\n(sweeps before 01:30 are INVALID)", col=OR)
    down(90.2, 88.4)

    dia(84, "G4 · SWEEP of Asian extreme INTO the POI,\ninside the window? (reach POI + reject)")
    nogo(84, "sweep outside window /\nno POI reach")
    down(79.8, 77.2)

    proc(74.2, "LTF TRIGGER (M1–M5, one structure, one signal)\nE-A turtle soup · E-B CSD · E-C MSS+FVG CE\nE-D first FVG CE · E-E IFVG/breaker", col=GN, h=8.0)
    down(70.2, 68)

    dia(63.6, "G5 · RISK: SL beyond POI/sweep extreme +\nbuffer · RR ≥ 3.0 to primary target?\nsize = risk% × equity / SL distance", col=RD)
    nogo(63.6, "STAND DOWN\n(no forced trades)")
    down(59.4, 56.8)

    proc(53.6, "EXECUTE — DEMO ONLY (fail-closed)\n1 trade/day · max 1 position · spread/staleness guards", col=GN)
    down(50.4, 48.6)

    proc(44.6, "MANAGE: P1 partial @ midnight open → TP1 Asia extreme\n→ TP2 low-resistance pool → TP3 prev-day extreme\nBE after P1 · stops only tighten · time-stop 12h", col=CY, h=8.0)
    down(40.6, 38.4)

    proc(35.2, "EXIT + JOURNAL (structure key · screenshots · R)\n→ cooldown until next NY day", col=PU)

    ax.text(X, 30.6, "any gate fail → NO-GO (never improvisable)  ·  invalid transitions: "
            "entry before G1–G4 · widening SL · re-using a consumed structure",
            color=SUB, fontsize=8.2, ha="center", va="top", wrap=True)

    ax.set_title("LKZ-1 · Decision pipeline — mirrors specs/lkz-v1.yaml §state_machine (5 hard gates)",
                 color=WH, fontsize=13.5, weight="bold", pad=10)
    save(fig, "lkz-fig5-decision-pipeline")


if __name__ == "__main__":
    fig1()
    fig2()
    fig3()
    fig4()
    fig5()
    print("done ->", OUT)
